fos_user:
    db_driver: orm 
    firewall_name: main
    user_class: App\Entity\User
    from_email:
        address: "bertrand.fernandez@gmail.com"
        sender_name: "bertrand.fernandez@gmail.com"
    registration:
      form:
        type:    App\AppBundle\Form\RegistrationFormType 
 